Lesson 05 task
EkBratchik/gocourse pull request #6
Opened 2021-07-20 10:09 UTC by EkBratchik

2021-07-20 14:52 UTC, dimonl approved these changes

2021-07-22 12:27 UTC, rat6666 requested changes

2021-07-22 12:27 UTC, rat6666 commented on lesson_05/main.go
> +	res,err := s.Area()
error is not handled. in golang you have to check if the error is not nil. in this case
res, err := s.Area() 
if err != nil {
    fmt.Println(err)
} else {
fmt.Printf("Area: %.2f ",res)
}
And please format you code before commit.

2021-07-22 14:48 UTC, rat6666 approved these changes

2021-07-22 15:10 UTC, merged